# Generated by Django 4.2.7 on 2023-11-27 16:51

from django.db import migrations, models
import django.utils.timezone
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='content',
            field=djrichtextfield.models.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Updated'),
            preserve_default=False,
        ),
    ]
