# Generated by Django 4.2.7 on 2023-11-27 17:09

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_content_category_created_category_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='content',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=djrichtextfield.models.RichTextField(blank=True, verbose_name='Description'),
        ),
    ]
